name: firstcal

dependencies: 
 - python=2.7
 - astropy=1.1.2
 - numpy=1.10.4
 - matplotlib
 - pyephem=3.7.5.2
 - jupyter=1.0.0
 - seaborn=0.7.1
 - pip:
  - git+https://github.com/zakiali/capo.git#egg=capo[complete]
  - git+https://github.com/zakiali/omnical.git#egg=omnical[complete]
  - git+https://github.com/zakiali/aipy.git#egg=aipy[complete]


