name: firstcal

dependencies: 
 -python=2.7
 -astropy=1.1.2
 -numpy=1.10.4
 -matplotlib
 -pyephem=3.7.5.2
 -jupyter=1.0.0
 -seaborn=0.7.1
 -pip:
  -git://github.com/zakiali/capo.git#egg=capo
  -git://github.com/zakiali/omnical.git#egg=omnical
  -git://github.com/zakiali/aipy.git#egg=aipy


